name: SimpleNightvision
version: 2.1
author: Maximilian1021
website: https://game-energy.de

main: me.Maximilian1021.main.main

commands:
  NV:
    description: Gibt dir Nightvision
    usage: /<command>
